(function() {var implementors = {};
implementors['gccjit'] = ["impl&lt;'ctx&gt; !<a class='trait' href='http://doc.rust-lang.org/nightly/core/marker/trait.Send.html' title='core::marker::Send'>Send</a> for <a class='struct' href='gccjit/struct.Type.html' title='gccjit::Type'>Type</a>&lt;'ctx&gt;","impl !<a class='trait' href='http://doc.rust-lang.org/nightly/core/marker/trait.Send.html' title='core::marker::Send'>Send</a> for <a class='struct' href='gccjit/struct.CompileResult.html' title='gccjit::CompileResult'>CompileResult</a>","impl&lt;'ctx&gt; !<a class='trait' href='http://doc.rust-lang.org/nightly/core/marker/trait.Send.html' title='core::marker::Send'>Send</a> for <a class='struct' href='gccjit/struct.Context.html' title='gccjit::Context'>Context</a>&lt;'ctx&gt;","impl&lt;'ctx&gt; !<a class='trait' href='http://doc.rust-lang.org/nightly/core/marker/trait.Send.html' title='core::marker::Send'>Send</a> for <a class='struct' href='gccjit/struct.Object.html' title='gccjit::Object'>Object</a>&lt;'ctx&gt;","impl&lt;'ctx&gt; !<a class='trait' href='http://doc.rust-lang.org/nightly/core/marker/trait.Send.html' title='core::marker::Send'>Send</a> for <a class='struct' href='gccjit/struct.Location.html' title='gccjit::Location'>Location</a>&lt;'ctx&gt;","impl&lt;'ctx&gt; !<a class='trait' href='http://doc.rust-lang.org/nightly/core/marker/trait.Send.html' title='core::marker::Send'>Send</a> for <a class='struct' href='gccjit/struct.Field.html' title='gccjit::Field'>Field</a>&lt;'ctx&gt;","impl&lt;'ctx, T&gt; !<a class='trait' href='http://doc.rust-lang.org/nightly/core/marker/trait.Send.html' title='core::marker::Send'>Send</a> for <a class='struct' href='gccjit/struct.Struct.html' title='gccjit::Struct'>Struct</a>&lt;'ctx, T&gt;","impl&lt;'ctx&gt; !<a class='trait' href='http://doc.rust-lang.org/nightly/core/marker/trait.Send.html' title='core::marker::Send'>Send</a> for <a class='struct' href='gccjit/struct.LValue.html' title='gccjit::LValue'>LValue</a>&lt;'ctx&gt;","impl&lt;'ctx&gt; !<a class='trait' href='http://doc.rust-lang.org/nightly/core/marker/trait.Send.html' title='core::marker::Send'>Send</a> for <a class='struct' href='gccjit/struct.RValue.html' title='gccjit::RValue'>RValue</a>&lt;'ctx&gt;","impl&lt;'ctx&gt; !<a class='trait' href='http://doc.rust-lang.org/nightly/core/marker/trait.Send.html' title='core::marker::Send'>Send</a> for <a class='struct' href='gccjit/struct.Parameter.html' title='gccjit::Parameter'>Parameter</a>&lt;'ctx&gt;","impl&lt;'ctx&gt; !<a class='trait' href='http://doc.rust-lang.org/nightly/core/marker/trait.Send.html' title='core::marker::Send'>Send</a> for <a class='struct' href='gccjit/struct.Function.html' title='gccjit::Function'>Function</a>&lt;'ctx&gt;","impl&lt;'ctx&gt; !<a class='trait' href='http://doc.rust-lang.org/nightly/core/marker/trait.Send.html' title='core::marker::Send'>Send</a> for <a class='struct' href='gccjit/struct.Block.html' title='gccjit::Block'>Block</a>&lt;'ctx&gt;",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
